// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiXs5VN1ZeDnGf1kLEFLhssmj_jXU7Ke8',
    appId: '1:211257649002:web:4b2ddb0349f554c57ee713',
    messagingSenderId: '211257649002',
    projectId: 'realtimedb-d4542',
    authDomain: 'realtimedb-d4542.firebaseapp.com',
    storageBucket: 'realtimedb-d4542.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLRoyBZJ1f7cFhWeEL9aC6Bw97zaJuQZA',
    appId: '1:211257649002:android:15ca1a923e0cd76d7ee713',
    messagingSenderId: '211257649002',
    projectId: 'realtimedb-d4542',
    storageBucket: 'realtimedb-d4542.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzk74HBbKzUcYP44HgqK72lwVgygJwMjo',
    appId: '1:211257649002:ios:722a85db280cca147ee713',
    messagingSenderId: '211257649002',
    projectId: 'realtimedb-d4542',
    storageBucket: 'realtimedb-d4542.appspot.com',
    iosClientId: '211257649002-5qj0503ei9h2gmdo0fals4ks5l4vrk9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtimefirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzk74HBbKzUcYP44HgqK72lwVgygJwMjo',
    appId: '1:211257649002:ios:722a85db280cca147ee713',
    messagingSenderId: '211257649002',
    projectId: 'realtimedb-d4542',
    storageBucket: 'realtimedb-d4542.appspot.com',
    iosClientId: '211257649002-5qj0503ei9h2gmdo0fals4ks5l4vrk9j.apps.googleusercontent.com',
    iosBundleId: 'com.example.realtimefirebase',
  );
}
